using Unity.Mathematics;
using UnityEngine;
using UnityEngine.InputSystem;

[RequireComponent(typeof(Rigidbody2D))]
public class PlayerMovement : MonoBehaviour
{
    [SerializeField] protected float m_speed = 6;
    protected Rigidbody2D m_rb2d;
    private Vector2 m_moveDir;
    private Vector2 MoveDir {
        get => m_moveDir;
        set {
            m_moveDir = value;
            m_moveDir = new(Mathf.Clamp(m_moveDir.x, -1, 1), Mathf.Clamp(m_moveDir.y, -1, 1));
        }
    }
    private SpriteRenderer m_spriteRenderer;
    private BoxCollider2D m_boxCol2d;
    private bool m_isColliding;


    private void Start()
    {
        m_rb2d = GetComponent<Rigidbody2D>();
        m_boxCol2d = GetComponent<BoxCollider2D>();
        m_spriteRenderer = GetComponentInChildren<SpriteRenderer>();
    }


    private void Update()
    {
        float xDir = 0;

        xDir += Keyboard.current.dKey.isPressed ||
            Keyboard.current.rightArrowKey.isPressed ? 1 : 0;

        xDir -= Keyboard.current.aKey.isPressed ||
            Keyboard.current.leftArrowKey.isPressed ? 1 : 0;
        

        float yDir = 0;

        yDir += Keyboard.current.wKey.isPressed ||
            Keyboard.current.upArrowKey.isPressed ? 1 : 0;

        yDir -= Keyboard.current.sKey.isPressed ||
            Keyboard.current.downArrowKey.isPressed ? 1 : 0;


        MoveDir = new(xDir, yDir);
    }

    private void FixedUpdate()
    {
        if (!m_isColliding) Move();
     }


    private void OnCollisionStay2D(Collision2D collider)
    {
        m_isColliding = true;
        if (collider.gameObject.CompareTag("Enemy")) {
            ResolveOverlaps();
        }
    }

    private void OnCollisionExit2D(Collision2D collision) => m_isColliding = false;

    private void Move()
    {
        m_rb2d.linearVelocity = m_moveDir * m_speed;

        Vector3 pos = m_rb2d.transform.position;
        Vector2 sizeAdjustment = new(m_spriteRenderer.size.x / 2, m_spriteRenderer.size.y / 2);
        pos.x = Mathf.Clamp(pos.x, ScreenBounds.Left + sizeAdjustment.x,
                            ScreenBounds.Right - sizeAdjustment.x);
        pos.y = Mathf.Clamp(pos.y, ScreenBounds.Bottom + sizeAdjustment.y,
                            ScreenBounds.Top - sizeAdjustment.y);
        m_rb2d.position = pos;
    }

    // generated by Claude. I understand what it does. I did have to modify it a little though. (It didn't even work at first)
    private void ResolveOverlaps() 
    {
        Collider2D[] nearby = Physics2D.OverlapBoxAll(m_rb2d.position, m_boxCol2d.size, quaternion.identity.value.z, LayerMask.GetMask("Default"));

        foreach (var other in nearby)
        {
            if (other == m_boxCol2d) continue;

            ColliderDistance2D dist = Physics2D.Distance(m_boxCol2d, other);
            
            if (dist.isOverlapped)
            {
                Vector2 pushOut = dist.normal * -dist.distance;

                m_rb2d.position += -pushOut * 1.5f;
            }
        }
    }
    //
}